---
apiVersion: hoprnet.org/v1alpha
kind: ClusterHoprd
metadata:
  name: hoprd-node-pr-1234
  namespace: riga
spec:
  network: monte_rosa
  ingress:
    enabled: true
  monitoring:
    enabled: true
  nodes:
    - name: default
      replicas: 2
      version: riga
      enabled: true 
      config:
        autoRedeemTickets: true
        announce: false
      #   networkQualityThreshold: 0.6
      # resources:
      #   limits:
      #     cpu: 1200m
      #     memory: 2Gi
      #   requests:
      #     cpu: 750m
      #     memory: 256Mi
