---
apiVersion: hoprnet.org/v1alpha
kind: Hoprd
metadata:
  name: hoprd-node-1
  namespace: riga
spec:
  environmentName: master-staging
  environmentType: production
  version: 1.93.0-next.10
  monitoring:
    enabled: true
  ingress:
    enabled: true
  # announce: true
  # autoRedeemTickets: true
  # networkQualityThreshold: 0.6