---
apiVersion: hoprnet.org/v1alpha
kind: Hoprd
metadata:
  name: hoprd-node-announced
  namespace: master-staging
spec:
  network: master-staging
  version: providence
  config:
    announce: true
  enabled: true 
  ingress:
    enabled: true
  monitoring:
    enabled: true
---
apiVersion: hoprnet.org/v1alpha
kind: Hoprd
metadata:
  name: hoprd-node-not-announced
  namespace: master-staging
spec:
  network: master-staging
  version: providence
  config:
    announce: false
  enabled: true 
  ingress:
    enabled: true
  monitoring:
    enabled: true

