---
apiVersion: hoprnet.org/v1alpha
kind: Hoprd
metadata:
  name: hoprd-node-1
  namespace: riga
spec:
  config:
    autoRedeemTickets: true
    announce: false
  #   networkQualityThreshold: 0.6
  enabled: true
  environmentName: monte_rosa
  ingress:
    enabled: true
  monitoring:
    enabled: true
  # resources:
  #   limits:
  #     cpu: 1200m
  #     memory: 2Gi
  #   requests:
  #     cpu: 750m
  #     memory: 256Mi
  version: riga


