---
apiVersion: hoprnet.org/v1alpha
kind: Hoprd
metadata:
  name: hoprd-node-1
  namespace: riga
spec:
  environmentName: monte_rosa
  environmentType: production
  version: riga
  monitoring:
    enabled: true
  ingress:
    enabled: true
  # announce: true
  # autoRedeemTickets: true
  # networkQualityThreshold: 0.6