---
apiVersion: hoprnet.org/v1alpha
kind: Hoprd
metadata:
  name: hoprd-node-1
  namespace: riga
spec:
  environmentName: monte_rosa
  environmentType: production
  version: riga
  monitoring:
    enabled: true
  ingress:
    enabled: true
    dnsDomain: stage.hoprtech.net
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: linode-issuer
  # announce: true
  # autoRedeemTickets: true
  # networkQualityThreshold: 0.6