---
apiVersion: hoprnet.org/v1alpha
kind: ClusterHoprd
metadata:
  name: pr-1234
  labels:
    hoprds.hoprnet.org/pullRequest: "1234"
  namespace:  rotsee
spec:
  network: rotsee
  ingress:
    enabled: true
  monitoring:
    enabled: true
  nodes:
    - name: default
      replicas: 2
      version: providence
      enabled: true 
      config:
        autoRedeemTickets: true
        announce: false
