---
apiVersion: hoprnet.org/v1alpha2
kind: ClusterHoprd
metadata:
  name: pr-1234
  labels:
    hoprds.hoprnet.org/pullRequest: "1234"
  namespace:  hoprd-operator
spec:
  identityPoolName: identity-pool-hoprd-operator
  replicas: 2
  version: 2.0.7
  enabled: true
  config: |
    host:
      address: !IPv4 0.0.0.0
      port: 9091
    identity:
      file: "/app/hoprd-db/.hoprd.id"
      password: "<REDACTED_PASS>"
      private_key:
    db:
      data: "/app/hoprd-db"
      initialize: true
      force_initialize: false
    inbox:
      capacity: 512
      max_age: 900
      excluded_tags:
      - 0
    api:
      enable: true
      auth: !Token "<REDACTED>"
      host:
        address: !IPv4 0.0.0.0
        port: 3001
    strategy:
      on_fail_continue: true
      allow_recursive: false
      finalize_channel_closure: true
      strategies:
    heartbeat:
      variance: 2000
      interval: 20000
      threshold: 60000
    network_options:
      min_delay: 1
      max_delay: 300
      quality_avg_window_size: 25
      quality_bad_threshold: 0.2
      quality_offline_threshold: 0.5
      quality_step: 0.1
      ignore_timeframe: 600
      backoff_exponent: 1.5
      backoff_min: 2
      backoff_max: 300
    healthcheck:
      enable: true
      host: 0.0.0.0
      port: 8080
    protocol:
      ack:
        timeout: 15
      heartbeat:
        timeout: 15
      msg:
        timeout: 15
      ticket_aggregation:
        timeout: 15
    network: rotsee
    chain:
      announce: true
      provider: https://rpc.ankr.com/gnosis
      check_unrealized_balance: true
    safe_module:
      safe_transaction_service_provider:
      safe_address:
        addr:
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
      module_address:
        addr:
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
          - 44
    test:
      announce_local_addresses: false
      prefer_local_addresses: false
      use_weak_crypto: false