---
apiVersion: hoprnet.org/v1alpha2
kind: ClusterHoprd
metadata:
  name: pr-1234
  labels:
    hoprds.hoprnet.org/pullRequest: "1234"
  namespace:  core-team
spec:
  identityPoolName: pull-requests-rotsee
  replicas: 1
  version: saint-louis-latest
  supportedRelease: saint-louis
  enabled: true
  service:
    type: LoadBalancer
  config: |
    hopr:
      chain:
        network: doufur
        provider: https://rpc.ankr.com/gnosis
