---
apiVersion: hoprnet.org/v1alpha2
kind: Hoprd
metadata:
  name: core-rotsee-1
  namespace: core-team
spec:
  version: saint-louis-latest
  identityPoolName: pull-requests-rotsee
  identityName: pull-requests-rotsee-1
  supportedRelease: kaunas
  deleteDatabase: false
  service:
    type: LoadBalancer
  enabled: true
  config: |
    hopr:
      chain:
        network: rotsee
        provider: http://gnosis-rpc-provider.rpc-provider.svc.cluster.local:8545
      strategy:
        on_fail_continue: true
        allow_recursive: false
        strategies: []

