instance:
  name: "hoprd-operator-staging"
  namespace: "staging"
  secret_name: "hoprd"
ingress:
  ingress_class_name: "nginx"
  dns_domain: "stage.hoprtech.net"
  annotations:
    cert-manager.io/cluster-issuer: "linode-issuer"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
hopli_image: europe-west3-docker.pkg.dev/hoprassociation/docker-images/hopli:latest