instance:
  name: hoprd-operator
  namespace: hoprd-operator
ingress:
  ingress_class_name: nginx
  dns_domain: prod.hoprnet.link
  loadbalancer_ip: 35.242.216.67
  annotations:
    cert-manager.io/cluster-issuer: "gcp-issuer"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
  namespace: ingress-nginx
  p2p_port_min: "9000"
  p2p_port_max: "9010"
  deployment_name: ingress-nginx-controller
hopli_image: europe-west3-docker.pkg.dev/hoprassociation/docker-images/hopli:2.1.0-rc.3
persistence:
  size: 500Mi
  storage_class_name: ceph-ephimeral