instance:
  name: hoprd-operator
  namespace: hoprd-operator
ingress:
  ingress_class_name: nginx
  dns_domain: staging.hoprnet.link
  loadbalancer_ip: 34.159.20.69
  namespace: ingress-nginx
  port_min: 9000
  port_max: 10000
  deployment_name: ingress-nginx-controller
  annotations:
    cert-manager.io/cluster-issuer: "gcp-issuer"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
hopli_image: europe-west3-docker.pkg.dev/hoprassociation/docker-images/hopli:2.1.4
logs_snapshot_url: https://storage.googleapis.com/hoprd-sync-data-staging/latest-stable.tar.gz
persistence:
  size: 4Gi
  storage_class_name: standard-rwo