environmentName: prod
operator:
  persistence:
    storageClassName: standard-rwo
  crossplane:
    provider:
      crossplane: gcp-crossplane
      upbound: gcp-upbound
    gcpProjectId: hopr-prod
    bucket:
      name: hoprd-sync-data-prod
      location: europe-west6
  fastSync:
    enabled: false
    schedule: "0 0 * * *"
    source:
      namespace: core-team
      deployment: core-node-1
  image:
    tag: latest
    pullPolicy: Always
  extraEnvVars: 
    - name: RUST_BACKTRACE
      value: full
    - name: RUST_LOG
      value: "hoprd_operator=DEBUG"
  ingress:
    ingressClassName: nginx
    dnsDomain: prod.hoprnet.link
    annotations:
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-headers: "x-auth-token,content-type,accept-content"
      cert-manager.io/cluster-issuer: "gcp-issuer"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    namespace: ingress-nginx
    loadBalancerIP: 35.242.216.67
    deploymentName: ingress-nginx-controller
adminUI:
  ingress:
    ingressClassName: nginx
    hostname: hoprd.prod.hoprnet.link
    annotations:
      nginx.ingress.kubernetes.io/server-snippets: |
          more_set_headers "Content-Security-Policy: upgrade-insecure-requests";





