
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hoprd-operator.fullname" . }}-scripts
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "hoprd-operator.labels" . | nindent 4 }}
    {{- if .Values.operator.commonLabels }}
    {{- .Values.operator.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.operator.commonAnnotations }}
  annotations:
    {{- .Values.operator.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
data:
  create-identity.sh: |
    #!/usr/bin/env bash

    set -Eeuo pipefail

    export PATH=${PATH}:/root/.foundry/bin/
    export RUST_BACKTRACE=full
    export PRIVATE_KEY=${DEPLOYER_PRIVATE_KEY}

    set -x
    sleep 99999999
    /bin/hopli identity --action create --identity-directory "/app/hoprd-identity-created" --identity-prefix .hoprd
    mv "/app/hoprd-identity-created/.hoprd0.id" "/app/hoprd-identity-created/.hoprd.id"
    /bin/hopli identity --action read --identity-directory "/app/hoprd-identity-created" | tee "/app/hoprd-identity-created/hoprd.json"
    /bin/hopli create-safe-module --network "${HOPRD_NETWORK}" --identity-from-path "/app/hoprd-identity-created/.hoprd.id" --hopr-amount "10" --native-amount "0.01" | tee "/app/hoprd-identity-created/safe.log"

  create-resource.sh: |
    #!/usr/bin/env bash

    set -Eeuo pipefail
    namespace=${1}
    identity_name=${2}

    set -x
    sleep 99999999
    declare -a safe_address, module_address, peer_id, native_address, identity_file
    safe_address=$(grep "Logs" -A 3 "/app/hoprd-identity-created/safe.log" | grep safeAddress | cut -d ' ' -f 4)
    module_address=$(grep "Logs" -A 3 "/app/hoprd-identity-created/safe.log" | grep safeAddress | cut -d ' ' -f 6)
    peer_id=$(jq -r '.[0].peer_id' /app/hoprd-identity-created/hoprd.json)
    native_address=$(jq -r '.[0].ethereum_address' /app/hoprd-identity-created/hoprd.json)
    identity_file=$(cat /app/hoprd-identity-created/.hoprd.id | base64 | tr -d '\n')
    cat <<EOF > "/app/hoprd-identity-created/identityHorpd.yaml"
    ---
    apiVersion: hoprnet.org/v1alpha
    kind: IdentityHoprd
    metadata:
      namespace: ${namespace}
      name: ${identity_name}
    spec:
      identityPoolName: core-staging
      identityFile: ${identity_file}
      peerId: "${peer_id}"
      nativeAddress: "${native_address}"
      safeAddress: "${safe_address}"
      moduleAddress: "${module_address}"
    EOF

    kubectl apply -f  /app/hoprd-identity-created/identityHorpd.yaml
