apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: identityhoprds.hoprnet.org
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "hoprd-operator.labels" . | nindent 4 }}
    {{- if .Values.operator.commonLabels }}
    {{- .Values.operator.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.operator.commonAnnotations }}
  annotations:
    {{- .Values.operator.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
spec:
  group: hoprnet.org
  names:
    kind: IdentityHoprd
    plural: identityhoprds
    singular: identityhoprd
    shortNames:
      - identityhoprd
  scope: Namespaced
  versions:
    - name: v1alpha2
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Phase
          type: string
          description: Identity phase
          jsonPath: .status.phase
        - name: Pool
          type: string
          description: Pool name
          jsonPath: .spec.identityPoolName
        - name: HoprdNode
          type: string
          description: Hoprd Name
          jsonPath: .status.hoprdNodeName
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          description: Schema definition for Identity Hoprd
          type: object
          properties:
            spec:
              type: object
              properties:
                identityPoolName:
                  type: string
                  description: 'Name of the Identity Pool'
                identityFile:
                  type: string
                  format: password
                  description: 'Contents of the hoprd identity file'
                peerId:
                  type: string
                  description: 'PeerId of the Hoprd node'
                nativeAddress:
                  type: string
                  description: 'Ethereum native address of the Hoprd node'
                safeAddress:
                  type: string
                  description: 'Ethereum address of the safe linked to the Hoprd node'
                moduleAddress:
                  type: string
                  description: 'Ethereum address of the module'
              required:
                - identityPoolName
                - identityFile
                - peerId
                - nativeAddress
                - safeAddress
                - moduleAddress
            status:
              description: The status object of IdentityHoprd node
              nullable: true
              properties:
                updateTimestamp:
                  format: date-time
                  type: string
                  description: Timestamp of the last applied change
                checksum:
                  type: string
                  description: Checksum of the last applied change
                phase:
                  description: Phase of the last applied change
                  type: string
                  enum:
                  - Initialized
                  - Failed
                  - Synching
                  - Ready
                  - InUse
                  - Deleting
                hoprdNodeName:
                  type: string
                  description: Name of the HoprdNode
              required: [ "updateTimestamp", "checksum", "phase"]
              type: object
          required:
          - spec