apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: identitypools.hoprnet.org
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "hoprd-operator.labels" . | nindent 4 }}
    {{- if .Values.operator.commonLabels }}
    {{- .Values.operator.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.operator.commonAnnotations }}
  annotations:
    {{- .Values.operator.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
spec:
  group: hoprnet.org
  names:
    kind: IdentityPool
    plural: identitypools
    singular: identitypool
    shortNames:
      - identitypool
  scope: Namespaced
  versions:
    - name: v1alpha
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Network
          type: string
          description: Hoprd network name
          jsonPath: .spec.network
        - name: Status
          type: string
          description: Identity status
          jsonPath: .status.status
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          description: Schema definition for Identity Hoprd
          type: object
          properties:
            spec:
              type: object
              properties:
                network:
                  type: string
                  description: 'Name of the Hoprd network'
                secretName:
                  type: string
                  description: Name of the secret containing sensitive data
                minReadyIdentities:
                  type: number
                  description: Number of ready instances to keep
              required:
                - network
                - secretName
                - minReadyIdentities
            status:
              description: The status object of IdentityHoprd node
              nullable: true
              properties:
                updateTimestamp:
                  format: date-time
                  type: string
                  description: Timestamp of the last applied change
                checksum:
                  type: string
                  description: Checksum of the last applied change
                status:
                  description: Status of the last applied change
                  type: string
                  enum:
                  - Initialized
                  - Failed
                  - OutOfSync
                  - Ready
                  - Deleting
                size:
                  description: Amount of identities created
                  type: number
                locked:
                  description: Amount of locked identities
                  type: number
              required: [ "updateTimestamp", "checksum", "status", "size", "locked"]
              type: object
          required:
          - spec