apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hoprds.hoprnet.org
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "hoprd-operator.labels" . | nindent 4 }}
    {{- if .Values.operator.commonLabels }}
    {{- .Values.operator.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.operator.commonAnnotations }}
  annotations:
    {{- .Values.operator.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
spec:
  group: hoprnet.org
  names:
    kind: Hoprd
    plural: hoprds
    singular: hoprd
    shortNames:
      - hoprd
  scope: Namespaced
  versions:
    - name: v1alpha
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Status
          type: string
          description: Hoprd status
          jsonPath: .status.status
        - name: IdentityHoprd
          type: string
          description: Hoprd Name
          jsonPath: .status.identityName
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          description: Schema definition for Hoprd Node
          type: object
          properties:
            spec:
              type: object
              properties:
                config:
                  type: string
                  description: Yaml configuration for Hoprd nodes
                enabled:
                  type: boolean
                  description: 'Flag indicating if the node should be started or stopped'
                deployment:
                  type: object
                  description: Deployment configuration
                  properties:
                    resources:
                      type: string
                      description: The definition for hardware resources to be used by the node deployment
                    startupProbe:
                      type: string
                      description: The definition of the startup probe to be used by the node deployment
                    livenessProbe:
                      type: string
                      description: The definition of the liveness probe to be used by the node deployment
                    readinessProbe:
                      type: string
                      description: The definition of the readiness probe to be used by the node deployment
                identityPoolName:
                  type: string
                  description: The name of the IdentityPool
                identityName:
                  type: string
                  description: The name of the IdentityHoprd
                version:
                  type: string
                  description: 'An specific hoprd version. Should match with a docker tag'
              required: ["version", "identityPoolName", "identityName"]
            status:
              description: The status object of Hoprd node
              nullable: true
              properties:
                updateTimestamp:
                  format: date-time
                  type: string
                  description: Timestamp of the last applied change
                checksum:
                  type: string
                  description: Checksum of the last applied change
                status:
                  description: Status of the last applied change
                  type: string
                  enum:
                  - Initializing
                  - Running
                  - Stopped
                  - Synching
                  - OutOfSync
                  - Deleting
                identityName:
                  type: string
                  description: Name of the HoprdNode
              required: [ "updateTimestamp", "checksum", "status"]
              type: object
          required:
          - spec