---
{{- if .Values.operator.fastSync.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
    name: hoprd-operator-fast-sync
    namespace: {{ .Values.operator.fastSync.source.namespace}}
    labels:
        hoprd-operator-fast-sync: create-snapshot
spec:
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 2
    schedule: "{{ .Values.operator.fastSync.schedule }}"
    jobTemplate:
        spec:
            backoffLimit: 1
            activeDeadlineSeconds: 300 # Timeout after 5 minutes
            ttlSecondsAfterFinished: 86400  # Cleanup completed jobs after 24 hour
            completions: 1
            template:
                metadata:
                spec:
                    containers:
                        - command:
                              - /bin/sh
                              - -c
                              - |
                                # Create backup
                                if ! tar czf /tmp/hopr_logs.tar.gz /app/hoprd-db/db/hopr_logs.db*; then
                                    echo "Failed to create backup archive"
                                    exit 1
                                fi

                                # Authenticate with GCP
                                if ! gcloud auth activate-service-account --key-file=/backup/key.json; then
                                    echo "Failed to authenticate with GCP"
                                    exit 1
                                fi

                                # Upload to GCS with verification
                                if ! gcloud storage cp /tmp/hopr_logs.tar.gz gs://{{ .Values.operator.crossplane.bucket.name }}/hopr_logs.tar.gz; then
                                    echo "Failed to upload backup"
                                    exit 1
                                fi

                                # Cleanup
                                rm -f /tmp/hopr_logs.tar.gz
                          image: gcr.io/google.com/cloudsdktool/google-cloud-cli:stable
                          name: fast-sync
                          resources:
                              limits:
                                  cpu: 500m
                                  memory: 512Mi
                          volumeMounts:
                              - name: hoprd-db
                                mountPath: /app/hoprd-db
                                readOnly: true
                              - name: service-account-key
                                mountPath: /backup/key.json
                                subPath: privateKey
                                readOnly: true
                    dnsPolicy: ClusterFirst
                    restartPolicy: Never
                    volumes:
                        - name: hoprd-db
                          persistentVolumeClaim:
                              claimName: {{ .Values.operator.fastSync.source.deployment }}
                        - name: service-account-key
                          secret:
                              secretName: hoprd-operator-sa-key
                              items:
                                  - key: privateKey
                                    path: privateKey
{{- end }}