---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hopr-operator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "hopr-operator.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.commonAnnotations }}
  annotations:
    {{- .Values.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hopr-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hopr-operator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: operator
        image: {{ printf "%s/%s:%s" .Values.image.registry .Values.image.repository .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        env:
        {{- if .Values.privateKey }}
          - name: PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                key: PRIVATE_KEY
                name: {{ include "hopr-operator.name" . }}
        {{- else }}
          - name: PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                key: {{ .Values.secretName }} 
                name: {{ .Values.secretKeyName }} 
        {{- end }}
          - name: OPERATOR_INSTANCE_NAME
            value: {{ include "hopr-operator.name" . }}
          - name: OPERATOR_INSTANCE_NAMESPACE
            value: {{ .Release.Namespace | quote }}
        volumeMounts:
          - name: hopr-repo-volume
            mountPath: /app/node_secrets
      serviceAccountName: {{ include "hopr-operator.name" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: hopr-repo-volume
          persistentVolumeClaim:
            claimName: {{ include "hopr-operator.fullname" . }}


