apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "hopr-operator.labels" . | nindent 4 }}
    {{- if .Values.operator.commonLabels }}
    {{- .Values.operator.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.operator.commonAnnotations }}
  annotations:
    {{- .Values.operator.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
  name: {{ include "hopr-operator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.operator.persistence.size }} 
  storageClassName: {{ .Values.operator.persistence.storageClassName }}
  volumeMode: Filesystem