{{- if .Values.operator.privateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hoprd-operator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "hoprd-operator.labels" . | nindent 4 }}
    {{- if .Values.operator.commonLabels }}
    {{- .Values.operator.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.operator.commonAnnotations }}
  annotations:
    {{- .Values.operator.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
type: Opaque
data:
  PRIVATE_KEY: {{ .Values.operator.privateKey | b64enc }}
{{- end }}
