{{- if .Values.privateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hopr-operator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "hopr-operator.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.commonAnnotations }}
  annotations:
    {{- .Values.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
type: Opaque
data:
  PRIVATE_KEY: {{ .Values.privateKey | b64enc }}
{{- end }}
