---
apiVersion: hoprnet.org/v1alpha3
kind: ClusterHoprd
metadata:
  name: {{ include "cluster-hoprd.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  identityPoolName: {{ include "cluster-hoprd.name" . }}
  replicas: {{ .Values.clusterHoprd.replicas }}
  version: {{ .Values.clusterHoprd.version | quote }}
  enabled: {{ .Values.clusterHoprd.enabled | default true }}
  deployment:
  {{- if .Values.clusterHoprd.nodes.deployment.env }}
    env: |
{{ .Values.clusterHoprd.nodes.deployment.env | indent 6 }}
  {{- end }}
  {{- if .Values.clusterHoprd.nodes.deployment.extraContainers }}
    extraContainers: |
{{ .Values.clusterHoprd.nodes.deployment.extraContainers | indent 6 }}
  {{- end }}
  {{- if .Values.clusterHoprd.nodes.deployment.livenessProbe }}
    livenessProbe: |
{{ .Values.clusterHoprd.nodes.deployment.livenessProbe | indent 6 }}
  {{- end }}
  {{- if .Values.clusterHoprd.nodes.deployment.readinessProbe }}
    readinessProbe: |
{{ .Values.clusterHoprd.nodes.deployment.readinessProbe | indent 6 }}
  {{- end }}
  {{- if .Values.clusterHoprd.nodes.deployment.resources }}
    resources: |
{{ .Values.clusterHoprd.nodes.deployment.resources | indent 6 }}
  {{- end }}
  {{- if .Values.clusterHoprd.nodes.deployment.startupProbe }}
    startupProbe: |
{{ .Values.clusterHoprd.nodes.deployment.startupProbe | indent 6 }}
  {{- end }}
  profilingEnabled: {{ .Values.clusterHoprd.profiling.enabled | default false }}
  service:
    type: {{ .Values.clusterHoprd.nodes.service.type }}
    portsAllocation: {{ .Values.clusterHoprd.nodes.service.portsAllocation }}
  config: {{ .Values.clusterHoprd.nodes.config | toYaml | nindent 4 }}
  {{ if .Values.clusterHoprd.logs.upload.enabled }}
  sourceNodeLogs: {{ .Values.clusterHoprd.logs.upload.sourceNode }}
  {{- end }}
  dnsName: {{ .Values.clusterHoprd.dnsName | quote }}
