{{- $release := .Release -}}
{{- $releaseName := include "cluster-hoprd.name" . -}}
{{- range $key, $value := .Values.clusterHoprd.identities }}
---
apiVersion: hoprnet.org/v1alpha2
kind: IdentityHoprd
metadata:
  name: {{ $key }}
  namespace: {{ $release.Namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  identityPoolName: {{ $releaseName }}
  identityFile: {{ $value.identityFile | quote }}
  nodeAddress: {{ $value.nodeAddress | quote }}
  safeAddress: {{ $value.safeAddress | quote }}
  moduleAddress: {{ $value.moduleAddress | quote }}
{{- end }}
