{{- $release := .Release -}}
{{- $releaseName := include "cluster-hoprd.name" . -}}
{{- $identities := .Values.clusterHoprd.identities -}}
{{- $keys := keys $identities | sortAlpha -}}
{{- $count := min (len $keys) (int .Values.clusterHoprd.replicas) -}}
{{- range $key := slice $keys 0 $count }}
{{- $value := index $identities $key }}
---
apiVersion: hoprnet.org/v1alpha3
kind: IdentityHoprd
metadata:
  name: {{ $key }}
  namespace: {{ $release.Namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  identityPoolName: {{ $releaseName }}
  identityFile: {{ $value.identityFile | quote }}
  nodeAddress: {{ $value.nodeAddress | quote }}
  safeAddress: {{ $value.safeAddress | quote }}
  moduleAddress: {{ $value.moduleAddress | quote }}
{{- end }}
