---
apiVersion: hoprnet.org/v1alpha2
kind: IdentityPool
metadata:
  name: {{ include "cluster-hoprd.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  network: {{ .Values.clusterHoprd.network }}
  secretName: {{ include "cluster-hoprd.name" . }}-wallet
  {{- if .Values.clusterHoprd.funding.enabled }}
  funding:
    schedule: {{ .Values.clusterHoprd.funding.schedule }}
    nativeAmount: {{ .Values.clusterHoprd.funding.nativeAmount | quote }}
  {{- end }}
