---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-hoprd.name" . }}-default-env
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    {{- if .Values.replicateDefaultEnvSecret.enabled }}
    replicator.v1.mittwald.de/replicate-from: hoprd-operator/hoprd-default-env
    {{- end }}
data:
  {{- range $key, $value := .Values.defaultHoprdEnvVars }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
