name: 'Build helm chart'
on:
  pull_request_target:
    branches:
      - master
    types: 
      - opened
      - ready_for_review
      - synchronize
      - reopened      
    paths:
      - "charts/**"
jobs:
  build-helm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}        
      - name: Check Helm chart version already exists
        run: |
          helm_chart_version=$(grep '^version:' Chart.yaml | sed 's/.*: /helm-/')
          echo "The Helm chart version is '${helm_chart_version}'"
          cat Chart.yaml
          if git tag -l | grep ${helm_chart_version} 1> /dev/null; then 
            echo "The Helm chart version '${helm_chart_version}' already exists. Please bump property 'version' on ./charts/Chart.yaml to a new version";
            exit 1
          fi
        working-directory: 'charts'
      - name: Lint
        run: |
          helm dependency update
          helm lint
        working-directory: 'charts'
