---

name: 'Container PR'

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "charts/**/*"

jobs:
  validate:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Google Cloud Credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}
          install_components: beta

      - name: Check if docker tag exists
        run: |
          hopr_operator_version=$(grep -A 1 "hopr_operator" Cargo.lock | grep version | sed 's/.* "//' | sed 's/"//' | tr -d '\n')
          images=$(gcloud container images  list-tags  gcr.io/hoprassociation/hoprd-operator --filter="tags[]=${hopr_operator_version}" 2> /dev/null)
          echo "gcr images: ${images}"
          if [ ! "${images}" = "" ]; then
            echo "The docker image tag '${hopr_operator_version}' already exists. Please bump Cargo.toml version";
            exit 1
          else
            echo "Building docker image tag '${hopr_operator_version}'";
          fi

  build:
    needs: validate
    runs-on: ubuntu-latest
    if: "!contains(github.event.pusher.name, 'dependabot')"

    steps:
      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: gcr.io/hoprassociation/hoprd-operator:latest
