---

name: 'Build Container'

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "charts/**/*"
concurrency:
  group: ${{ github.head_ref }}-container
  cancel-in-progress: true
jobs:
  bump_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump Cargo version
        id: bumping_version
        run: |
          hoprd_operator_version=$(grep "^version = " Cargo.toml | sed 's/.* "//' | sed 's/"$//' | tr -d '\n')
          git_tag=$(git tag -l ${hoprd_operator_version})
          echo "Workspace version is ${hoprd_operator_version} while tagged is ${git_tag}"
          if [ "${git_tag}" = "${hoprd_operator_version}" ]; then
            patch_number=$(echo $git_tag | sed 's/.*\.//')
            release_number=$(echo $git_tag | sed "s/\.${patch_number}//")
            bump_version=${release_number}.$((patch_number + 1))
            echo "The version ${git_tag} already exists, bumping to version ${bump_version}";
            sed -i "s/^version = \"${git_tag}\"/version = \"${bump_version}\"/" Cargo.toml
            echo "bumped_version=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        if: ${{ steps.bumping_version.outputs.bumped_version }}
        with:
          toolchain: stable

      # Update Cargo.lock
      - name: Build Cargo
        uses: actions-rs/cargo@v1
        with:
          command: build
      
      - name: Commit and push
        if: ${{ steps.bumping_version.outputs.bumped_version }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump cargo version
          repository: .
          commit_user_name: HOPR CI robot
          commit_user_email: noreply@hoprnet.org
          commit_author: HOPR CI robot <noreply@hoprnet.org>
          skip_fetch: false
          skip_checkout: false
          create_branch: false

  build:
    needs: bump_version
    runs-on: ubuntu-latest
    steps:
      - name: Build container image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: gcr.io/hoprassociation/hoprd-operator:latest
