---

name: 'Container merge'

on:
  push:
    branches:
      - master
    paths-ignore:
      - "charts/**/*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Google Cloud Credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}
          install_components: beta

      - name: Google Container authentication
        run: gcloud auth configure-docker --quiet gcr.io

      - name: Get package version
        run: |
          docker_tag=$(grep -A 1 "hopr_operator" Cargo.lock | grep version | sed 's/.* "//' | sed 's/"//' | tr -d '\n')
          echo "DOCKER_TAG=${docker_tag}" >> $GITHUB_ENV

      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            gcr.io/hoprassociation/hoprd-operator:${{ env.DOCKER_TAG }}
            gcr.io/hoprassociation/hoprd-operator:latest

      - name: Tag Docker version
        run: |
            git config user.email "noreply@hoprnet.org"
            git config user.name "HOPR CI robot"
            git tag ${{ env.DOCKER_TAG }}
            git push origin ${{ env.DOCKER_TAG }}
