---

name: 'Helm chart publish'

on:
  push:
    branches:
      - master
    paths:
      - "charts/**"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Helm chart version
        run: |
          HELM_CHART_VERSION=$(grep '^version:' Chart.yaml | sed 's/.*: //')
          echo "HELM_CHART_VERSION=helm-${HELM_CHART_VERSION}" >> $GITHUB_ENV
        working-directory: 'charts/hoprd-operator/'

      - name: Tag Helm version
        run: |
            git config user.email "noreply@hoprnet.org"
            git config user.name "HOPR CI robot"
            git tag ${{ env.HELM_CHART_VERSION }}
            git push origin ${{ env.HELM_CHART_VERSION }}
