---

name: 'Helm chart'

on:
  pull_request:
    branches:
      - master
    paths:
      - 'charts/hoprd-operator/values.yaml'

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install readme-generator-for-helm
        run: npm install -g @bitnami/readme-generator-for-helm@2.5.0

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      - name: Execute readme-generator-for-helm
        run: |
          readme-generator --values "charts/hoprd-operator/values.yaml" --readme "charts/hoprd-operator/README.md" --schema "/tmp/schema.json"

      - name: Push changes
        run: |
          # Push all the changes
          if git status -s | grep charts; then
            git config user.email "noreply@hoprnet.org"
            git config user.name "HOPR CI robot"
            git config pull.rebase false
            git add . && git commit -am "Update parameters README.md" --signoff && git push
          fi
