---

name: 'Helm chart build'

on:
  pull_request:
    paths:
      - "charts/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate Helm chart version
        run: |
          HELM_CHART_VERSION=$(grep '^version:' Chart.yaml | sed 's/.*: //')
          echo "HELM_CHART_VERSION=${HELM_CHART_VERSION}" >> $GITHUB_ENV
          echo "The Helm chart version is '${HELM_CHART_VERSION}'"
          if git tag -l | grep helm-${HELM_CHART_VERSION} 1> /dev/null; then
            echo "The Helm chart version '${HELM_CHART_VERSION}' already exists. Please bump property 'version' on ./charts/Chart.yaml to a new version";
            exit 1
          fi
        working-directory: 'charts/hoprd-operator/'

  lint:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint
        run: |
          helm dependency update
          helm lint
        working-directory: 'charts/hoprd-operator/'
