---

name: 'Publish Helm chart CRDs'

on:
  push:
    branches:
      - master
    paths:
      - "charts/hoprd-crds/**"
concurrency:
  group: ${{ github.head_ref }}-crds-publish
  cancel-in-progress: false
jobs:
  publish:
    runs-on: depot-ubuntu-24.04
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Generate short-lived github token from GitHub App Hoprnet
        id: bot-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.GH_APP_HOPRNET_BOT_CLIENT_ID }}
          private-key: ${{ vars.GH_APP_HOPRNET_BOT_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.bot-token.outputs.token }}

      - name: Get Helm chart version
        id: get_version
        run: |
          HELM_CHART_VERSION=$(grep '^version:' Chart.yaml | sed 's/.*: //')
          echo "HELM_CHART_VERSION=${HELM_CHART_VERSION}" >> $GITHUB_OUTPUT
        working-directory: 'charts/hoprd-crds/'

      - name: Setup GCP
        id: gcp
        uses: hoprnet/hopr-workflows/actions/setup-gcp@45221eb1aadfc5c46751306c5c7d6d291c8a24b3
        with:
          login_artifact_registry: 'true'

      - name: Helm Package
        run: |
          helm package . --version ${{ steps.get_version.outputs.HELM_CHART_VERSION }}
        working-directory: 'charts/hoprd-crds/'

      - name: Helm Publish
        run: |
          helm push hoprd-crds-${{ steps.get_version.outputs.HELM_CHART_VERSION }}.tgz oci://europe-west3-docker.pkg.dev/hoprassociation/helm-charts
        working-directory: 'charts/hoprd-crds/'

      - name: Tag Helm version
        run: |
            git config user.email "noreply@hoprnet.org"
            git config user.name "HOPR CI robot"
            git tag helm-hoprd-crds-${{ steps.get_version.outputs.HELM_CHART_VERSION }}
            git push origin helm-hoprd-crds-${{ steps.get_version.outputs.HELM_CHART_VERSION }}
