---

name: 'Publish Helm chart Cluster'

on:
  push:
    branches:
      - master
    paths:
      - "charts/cluster-hoprd/**"
concurrency:
  group: ${{ github.head_ref }}-cluster
  cancel-in-progress: false
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Helm chart version
        id: get_version
        run: |
          HELM_CHART_VERSION=$(grep '^version:' Chart.yaml | sed 's/.*: //')
          echo "HELM_CHART_VERSION=${HELM_CHART_VERSION}" >> $GITHUB_OUTPUT
        working-directory: 'charts/cluster-hoprd/'

      - name: Set up Google Cloud Credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}
          install_components: beta

      - name: Artifact Registry authentication
        run: make gcp-login

      - name: Helm Package
        run: |
          helm package . --version ${{ steps.get_version.outputs.HELM_CHART_VERSION }}
        working-directory: 'charts/cluster-hoprd/'
      - name: Helm Publish
        run: |
          helm push cluster-hoprd-${{ steps.get_version.outputs.HELM_CHART_VERSION }}.tgz oci://europe-west3-docker.pkg.dev/hoprassociation/helm-charts
        working-directory: 'charts/cluster-hoprd/'

      - name: Tag Helm version
        run: |
            git config user.email "noreply@hoprnet.org"
            git config user.name "HOPR CI robot"
            git tag helm-cluster-hoprd-${{ steps.get_version.outputs.HELM_CHART_VERSION }}
            git push origin helm-cluster-hoprd-${{ steps.get_version.outputs.HELM_CHART_VERSION }}
